### PR TITLE
 Add recordings to recordings page.

### PR DESCRIPTION
**Pull request by IRHM**
Add recordings to recordings page.

### CODE REVIEW

**Comment by IRHM** [comment]
;(

**Comment by DanyaalA** [comment]
This is good

**Review by DanyaalA — COMMENTED** [review]
Works

**Review by DanyaalA — COMMENTED** [review]
Good Stuff

**Review by DanyaalA — COMMENTED** [review]
Good

**Review by DanyaalA — APPROVED** [review]
Good Stuff

**Pull request merged**
